### ISSUE TITLE
generateur de site statique

### ISSUE THREAD

**Issue by Its-Just-Nans** [lettre-hebdomadaire/lettre-hebdomadaire.github.io#3]
Salut,

Pourquoi le pas utiliser un generateur de site statique ?

Ça permettrait de vous éviter de vous embetter avec le html et écrire juste les articles en markdown

Exemple : 
- jekyll (ruby)
- Hugo (go)
- Zola (Rust)

**Comment by lettre-hebdomadaire** [comment]
Salut,
Pour le moment comme c'est pas un gros site ça marche plutôt bien comme on fait, mais peut-être qu'un jour on regardera ça !
